OrderManagement/Areas/Authority/Controllers/PermissionBaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace OrderManagement.Areas.Authority.Controllers
{
    [Area("Authority")]
    public class PermissionBaseController : Controller
    {
        public IConfiguration Configuration { get; }
        public PermissionBaseController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public List<OrderManagementModel.DBModel.Authority.Authority_PermissionBase> Index()
        {
            OrderManagementBll.Authority.PermissionBase AccountBll = new OrderManagementBll.Authority.PermissionBase(Configuration);

            return AccountBll.GetPermissionList();
        }
    }
}

OrderManagement/Areas/Authority/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using OrderManagementModel;
using OrderManagementModel.Common;

namespace OrderManagement.Areas.Authority.Controllers
{
    [Area("Authority")]
    public class RoleController : Controller
    {
        public IConfiguration Configuration { get; }
        public RoleController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public List<OrderManagementModel.DBModel.Authority.Authority_Role> Index()
        {
            OrderManagementBll.Authority.Role AccountBll = new OrderManagementBll.Authority.Role(Configuration);

            return AccountBll.GetRoleList();
        }
        public HQResult<string> RelatedPerBase(int BaseId, int RoleId)
        {
            OrderManagementBll.Authority.Role Bll = new OrderManagementBll.Authority.Role(Configuration);

            return Bll.RelatedPerBase(RoleId, BaseId);
        }
        public HQResult<string> AddRole(string RoleName, string Description)
        {
            OrderManagementBll.Authority.Role Bll = new OrderManagementBll.Authority.Role(Configuration);

            return Bll.AddRole(RoleName, Description);
        }
    }
}

OrderManagement/Areas/Main/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace OrderManagement.Areas.Main.Controllers
{
    [Area("main")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Error()
        {
            var feature = this.HttpContext.Features.Get<IExceptionHandlerFeature>();
            var error = feature?.Error;

            if (error == null)
            {
                return View();
            }

            ViewData["error"] = Newtonsoft.Json.JsonConvert.SerializeObject(error);

            Console.Write(ViewData["error"]);

            return View();
        }
    }
}

OrderManagement/Areas/Main/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        div {
            margin-top: 2px;
            margin-bottom: 2px;
            padding-top: 2px;
            padding-bottom: 2px;
        }
    </style>
</head>
<body>
    <div>
        <div> <div> @Html.ActionLink("退出", "Sigout", "Authority", new { area = "Authority" }) </div></div>
        <div>
            用户列表: <a target="_blank" href="@Url.Action("index","Account")">用户列表 </a>
            <div>
                添加用户: <div>
                    <form target="_blank" method="post" action="@Url.Action("AddAccount","account",new {area="authority" })">

                        <label>Account:<input type="text" name="Account" /></label>
                        <label>Pass:<input type="text" name="Pass" /></label>
                        <label>Name:<input type="text" name="Name" /></label>
                        <input type="submit" value="添加" />
                    </form>
                </div>
            </div>
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
        <div>
            角色列表: <a target="_blank" href="@Url.Action("index","Role")">角色列表</a>
            <div>
                添加角色: <div>
                    <form target="_blank" method="post" action="@Url.Action("AddRole","Role",new {area="authority" })">
                        <label>RoleName:<input type="text" name="RoleName" /></label>
                        <label>Description:<input type="text" name="Description" /></label>
                        <input type="submit" value="添加" />
                    </form>
                </div>
            </div>
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
        <div>
            基础权限: <a target="_blank" href="@Url.Action("index","PermissionBase")">基础权限</a>
            @*<div>
                    添加用户: <div>
                        <form target="_blank" method="post" action="@Url.Action("AddRole","account",new {area="authority" })">
                            <label>用户id:<input type="text" name="AccountId" /></label>
                            <label>角色id:<input type="text" name="RoleId" /></label>
                            <input type="submit" value="添加" />
                        </form>
                    </div>
                </div>*@
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
        <div>
            用户关联角色: <div>
                <form target="_blank" method="post" action="@Url.Action("RelatedRole","account",new {area="authority" })">
                    <label>用户id:<input type="text" name="AccountId" /></label>
                    <label>角色id:<input type="text" name="RoleId" /></label>
                    <input type="submit" value="添加" />
                </form>
            </div>
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
        <div>
            角色关联权限: <div>
                <form target="_blank" method="post" action="@Url.Action("RelatedPerBase","Role",new {area="authority" })">
                    <label>权限id:<input type="text" name="BaseId" /></label>
                    <label>角色id:<input type="text" name="RoleId" /></label>
                    <input type="submit" value="添加" />
                </form>
            </div>
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
        <div>
            权限测试页面: <div>
                <a target="_blank" href="@Url.Action("a1","test1",new {area="test" })">a1 </a><br />
                <a target="_blank" href="@Url.Action("a2","test1",new {area="test" })">a2 </a><br />
                <a target="_blank" href="@Url.Action("a3","test1",new {area="test" })">a3 </a><br />
                <a target="_blank" href="@Url.Action("a4","test1",new {area="test" })">a4 </a><br />
            </div>
        </div>
        <div style="height:1px;width:100%;background-color:forestgreen"></div>
    </div>
</body>
</html>